config container 'test'
    option enabled '0'
    option privileged '0'
    option name 'test'
    option image 'quay.io/podman/hello'
    option platform 'linux/amd64'
    option delay '5s'
    option memory '512m'
    option softmem '128m'
    option hostname 'hello'
    option ip '172.17.1.1'
    option ip6 'fd00::1'
    option pid 'host'
    option pull 'try'
    option restart 'unless-stopped'
    option cpus '0.5'
    option priority '1024'
    list dns '1.1.1.1'
    list dns '8.8.8.8'
    list env 'TZ=Europe/Berlin'
    list volume '/etc/openwrt_release:/etc/openwrt_release:ro'
    list volume '/home/test_container/etc/:/etc/test'
    list cmd 'ping'
    list cmd '-c'
    list cmd '4'
    list cmd '172.17.0.1'
    list label 'app=hello'
    list label 'env=example'