config container 'test'
    option enabled '0'
    option privileged '0'
    option name 'test'
    option dns '1.1.1.1'
    option image 'quay.io/podman/hello'
    option memory '64m'
    option hostname 'hello'
    option ip '172.17.1.1'
    option pid 'host'
    option restart 'unless-stopped'
    list env 'TZ=Europe/Berlin'
    list volume '/etc/openwrt_release:/etc/openwrt_release:ro'
    list volume '/home/test_container/etc/:/etc/test'
    list cmd 'ping'
    list cmd '-c'
    list cmd '4'
    list cmd '172.17.0.1'
    list label 'app=hello'
    list label 'env=example'